language: erlang

otp_release:
   - 17.4

addons:
  apt:
    sources:
      - boost-latest
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - automake
      - clang-3.7
      - libboost1.55-all-dev
      - python3

script:
  - CXX=clang++-3.7 ./configure
  - touch TAGS.root
  - make
  - make cpp
  - make python
  - make python3
  - make java
