language: erlang

otp_release:
   - 17.4

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - automake
      - clang
      - libboost1.55-all-dev
      - python3

script:
  - CXX=clang++ ./configure
  - touch TAGS.root
  - make
  - make cpp
  - make python
  - make python3
  - make java
