language: erlang

otp_release:
   - 18.1

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - automake
      - g++
      - libboost1.55-all-dev
      - python3

script:
  - ./configure
  - touch TAGS.root
  - make
  - make cpp
  - make python
  - make python3
  - make java
